### ISSUE TITLE
Updated schema for eIDAS MDSL

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/schemas#36]
The XML Schema for MDSL has been updated since format specification version 1.2.

This update changed the metadata certificate input to unbounded.

This was done without changing the version or the schema identifier of the XML Schema.

Those who implement this updated version are backwards compatible with old MDSL. However old implementations using the old schema will fail new MDSL with multiple certificates.

Users of this new schema should update the schema as soon as possible.

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/schemas/pull/35
